"""
Manufacturing module API — FG item creation, BOM builder helpers.
"""
import json
import re

import frappe
from frappe.utils import cint, flt


def _upsert_product_library(fg_item_code, cost_item=None, customer_ref=None, overrides=None):
	"""Create a Product Library record for a new FG, pre-filled from the (final) cost Item
	and its Calculation Breakdown. `overrides` (a dict keyed by Product Library fieldname)
	wins over the computed defaults — used when the user reviews/edits the details in the
	FG-creation popup. Non-fatal — never blocks FG creation."""
	try:
		if not fg_item_code or not frappe.db.exists("DocType", "Product Library"):
			return
		if frappe.db.exists("Product Library", {"fg_item": fg_item_code}):
			return

		item = frappe.db.get_value(
			"Item", fg_item_code, ["item_name", "customer_ref"], as_dict=True
		) or {}

		ci = {}
		cb = {}
		if cost_item and frappe.db.exists("cost Item", cost_item):
			ci = frappe.db.get_value(
				"cost Item", cost_item,
				["customer_ref", "colour", "inquiry", "cut_sheet_l", "cut_sheet_w"],
				as_dict=True,
			) or {}
			cb_name = frappe.db.get_value(
				"Cost Item Calculation", {"parent": cost_item},
				"calculation_breakdown", order_by="idx asc",
			)
			if cb_name and frappe.db.exists("Calculation Breakdown", cb_name):
				cb = frappe.db.get_value(
					"Calculation Breakdown", cb_name,
					["name", "pricing_type", "no_of_colors", "no_of_ups",
					 "full_sheet_l", "full_sheet_w", "cut_sheet_l", "cut_sheetw",
					 "ui_state"],
					as_dict=True,
				) or {}

		pricing = (cb.get("pricing_type") or "").strip()
		# Flexo reel/product dimensions live only in the CB ui_state JSON.
		w = l = 0
		if cb.get("ui_state"):
			try:
				form = (json.loads(cb["ui_state"]) or {}).get("form", {}) or {}
				w = flt(form.get("reel_width_mm") or form.get("product_width_mm") or 0)
				l = flt(form.get("product_length_mm") or 0)
			except Exception:
				pass

		def _size(a, b):
			a, b = flt(a), flt(b)
			return f"{a} x {b}" if (a or b) else ""

		pl_data = {
			"doctype":               "Product Library",
			"product_code":          fg_item_code,
			"product_name":          item.get("item_name") or fg_item_code,
			"customer_product_code": customer_ref or item.get("customer_ref") or ci.get("customer_ref") or "",
			"department":            pricing if pricing in ("Offset", "Flexo") else "",
			"flexo_type":            "Reel" if pricing == "Flexo" else "",
			"fg_item":               fg_item_code,
			"cost_item":             cost_item or "",
			"calculation_breakdown": cb.get("name") or "",
			"inquiry":               ci.get("inquiry") or "",
			"no_of_colors":          cint(cb.get("no_of_colors") or ci.get("colour") or 0),
			"no_of_ups":             cint(cb.get("no_of_ups") or 0),
			"full_sheet_size":       _size(cb.get("full_sheet_l"), cb.get("full_sheet_w")),
			"cut_sheet_size":        _size(cb.get("cut_sheet_l") or ci.get("cut_sheet_l"),
			                               cb.get("cut_sheetw") or ci.get("cut_sheet_w")),
			"width_mm":              w,
			"length_mm":             l,
		}
		# User-reviewed overrides (from the FG-creation popup) win over defaults.
		if overrides and isinstance(overrides, dict):
			meta = frappe.get_meta("Product Library")
			for k, v in overrides.items():
				if v in (None, "") or not meta.has_field(k):
					continue
				pl_data[k] = v
		pl = frappe.get_doc(pl_data)
		pl.flags.ignore_permissions = True
		pl.insert(ignore_permissions=True)
		if frappe.db.has_column("Item", "custom_product_library"):
			frappe.db.set_value("Item", fg_item_code, "custom_product_library", pl.name)
	except Exception:
		frappe.log_error(
			title="pricing_calculator: product library upsert failed",
			message=frappe.get_traceback(),
		)


@frappe.whitelist()
def create_fg_item(item_name, description, item_group, department, stock_uom="Nos",
                   cost_item=None, customer_ref=None, pl_overrides=None):
	"""
	Create a Finished Good ERPNext Item with all mandatory custom fields resolved.
	- custom_department_abbr  fetched from Department.custom_abbr
	- custom_item_group_abbr  fetched from Item Group.custom_abbr
	- custom_cost_item        links the FG to its Cost Item (→ calculation breakdown for BOM)
	Item code is auto-generated by ERPNext naming series.
	"""
	if not item_name:
		frappe.throw("Item Name is required")
	if not item_group:
		frappe.throw("Item Group is required")
	if not department:
		frappe.throw("Department is required")

	# Resolve abbreviations from the linked masters
	item_group_abbr = frappe.db.get_value("Item Group", item_group, "custom_abbr") or ""
	dept_abbr       = frappe.db.get_value("Department", department, "custom_abbr") or ""

	doc = frappe.get_doc({
		"doctype":                "Item",
		"item_name":              item_name,
		"description":            description or item_name,
		"item_group":             item_group,
		"stock_uom":              stock_uom or "Nos",
		"is_stock_item":          1,
		"is_sales_item":          1,
		"is_purchase_item":       0,
		"custom_department":      department,
		"custom_department_abbr": dept_abbr,
		"custom_item_group_abbr": item_group_abbr,
	})
	if cost_item and frappe.db.has_column("Item", "custom_cost_item"):
		doc.custom_cost_item = cost_item
	if customer_ref and frappe.db.has_column("Item", "customer_ref"):
		doc.customer_ref = customer_ref
	doc.insert(ignore_permissions=True)
	if isinstance(pl_overrides, str):
		pl_overrides = json.loads(pl_overrides or "{}")
	_upsert_product_library(doc.name, cost_item, customer_ref, overrides=pl_overrides)
	frappe.db.commit()

	return {"item_code": doc.name, "item_name": doc.item_name}


def _variant_abbr(value):
	"""Short unique-ish abbreviation for an Item Attribute value."""
	a = re.sub(r"[^A-Za-z0-9]+", "", value or "").upper()[:10]
	return a or (value or "")[:10]


def _ensure_item_attribute(attribute, values):
	"""Create the Item Attribute if missing and make sure all values exist on it.

	Abbreviations must be unique within the attribute, and standard attributes
	like "Size" already ship with Small=S / Medium=M / Large=L. So we skip values
	that already exist and generate a non-colliding abbr for genuinely new ones.
	"""
	attribute = (attribute or "Size").strip()
	is_new = not frappe.db.exists("Item Attribute", attribute)
	doc = (frappe.get_doc({"doctype": "Item Attribute", "attribute_name": attribute})
	       if is_new else frappe.get_doc("Item Attribute", attribute))

	existing_vals  = {(r.attribute_value or "").lower() for r in doc.item_attribute_values}
	existing_abbrs = {(r.abbr or "").upper() for r in doc.item_attribute_values}

	changed = False
	for v in values:
		if v.lower() in existing_vals:
			continue
		base = _variant_abbr(v)
		abbr, n = base, 1
		while abbr.upper() in existing_abbrs:
			n += 1
			abbr = f"{base}{n}"
		doc.append("item_attribute_values", {"attribute_value": v, "abbr": abbr})
		existing_vals.add(v.lower())
		existing_abbrs.add(abbr.upper())
		changed = True

	if is_new:
		doc.insert(ignore_permissions=True)
	elif changed:
		doc.save(ignore_permissions=True)
	frappe.db.commit()
	return attribute


@frappe.whitelist()
def create_fg_variants(template_name, description, item_group, department,
                       stock_uom="Nos", attribute="Size", variants=None, cost_item=None,
                       pl_overrides=None):
	"""
	Create each variation as its OWN independent Finished Good Item (no ERPNext
	template/variant relationship). All variants share one Cost Item.

	variants = JSON list of {value, item_name, customer_ref}.
	  • value        — short label used to auto-name the item (e.g. "S"); optional
	  • item_name    — item name (auto = base + " - " + value if blank); editable
	  • customer_ref — per-item customer reference code

	pl_overrides = reviewed Product Library values (shared across variants). Each variant's
	Product Library Customer Product Code is set from its own customer_ref; each variant Item
	is stamped with custom_variant_type = attribute and custom_variant_value = its value.
	"""
	if isinstance(variants, str):
		variants = json.loads(variants or "[]")
	variants = variants or []
	if isinstance(pl_overrides, str):
		pl_overrides = json.loads(pl_overrides or "{}")
	pl_overrides = pl_overrides or {}
	rows = [v for v in variants if (v.get("value") or v.get("item_name") or "").strip()]
	if not rows:
		frappe.throw("Add at least one variation (a value like S/M/L or an item name).")
	if not item_group:
		frappe.throw("Item Group is required")
	if not department:
		frappe.throw("Department is required")

	ig_abbr   = frappe.db.get_value("Item Group", item_group, "custom_abbr") or ""
	dept_abbr = frappe.db.get_value("Department", department, "custom_abbr") or ""
	has_cust_ref = frappe.db.has_column("Item", "customer_ref")
	has_var_type = frappe.db.has_column("Item", "custom_variant_type")
	has_var_val  = frappe.db.has_column("Item", "custom_variant_value")

	created = []
	for r in rows:
		val   = (r.get("value") or "").strip()
		vname = (r.get("item_name") or "").strip() or (f"{template_name} - {val}" if val else template_name)
		doc = frappe.get_doc({
			"doctype":                "Item",
			"item_name":              vname,
			"description":            description or vname,
			"item_group":             item_group,
			"stock_uom":              stock_uom or "Nos",
			"is_stock_item":          1,
			"is_sales_item":          1,
			"is_purchase_item":       0,
			"custom_department":      department,
			"custom_department_abbr": dept_abbr,
			"custom_item_group_abbr": ig_abbr,
		})
		if has_cust_ref:
			doc.customer_ref = (r.get("customer_ref") or "").strip()
		# Stamp the variant identity onto the Item (e.g. Size / S)
		if has_var_type:
			doc.custom_variant_type = attribute
		if has_var_val:
			doc.custom_variant_value = val
		# All variants link to the one shared Cost Item (→ its calculation breakdown)
		if cost_item and frappe.db.has_column("Item", "custom_cost_item"):
			doc.custom_cost_item = cost_item
		doc.insert(ignore_permissions=True)
		# Shared reviewed PL values, but each variant keeps its own customer product code.
		row_over = dict(pl_overrides)
		if r.get("customer_ref"):
			row_over["customer_product_code"] = r.get("customer_ref")
		_upsert_product_library(doc.name, cost_item, r.get("customer_ref"), overrides=row_over)
		created.append({"item_code": doc.name, "item_name": doc.item_name,
		                "value": val, "customer_ref": r.get("customer_ref") or ""})

	# Shared Cost Item — store the base customer ref (first row)
	if cost_item and frappe.db.exists("cost Item", cost_item):
		base_ref = (rows[0].get("customer_ref") or "").strip()
		if base_ref:
			frappe.db.set_value("cost Item", cost_item, "customer_ref", base_ref)

	frappe.db.commit()
	return {"items": created}


# ── Customer creation + FG list (for the quotation → SO flow) ──

def _default_customer_group():
	return (frappe.db.get_single_value("Selling Settings", "customer_group")
	        or ("All Customer Groups" if frappe.db.exists("Customer Group", "All Customer Groups")
	            else frappe.db.get_value("Customer Group", {"is_group": 0}, "name")))


def _default_territory():
	return (frappe.db.get_single_value("Selling Settings", "territory")
	        or ("All Territories" if frappe.db.exists("Territory", "All Territories")
	            else frappe.db.get_value("Territory", {"is_group": 0}, "name")))


@frappe.whitelist()
def create_customer_from_quotation(quotation):
	"""Create (or find) a Customer from a lead/prospect-based quotation and link it."""
	doc = frappe.get_doc("Savinda Quotation", quotation)
	if doc.customer:
		return {"customer": doc.customer, "existing": True}

	name = (doc.customer_name or "").strip()
	if not name:
		frappe.throw("No Customer Name on this quotation to create a customer from.")

	existing = frappe.db.get_value("Customer", {"customer_name": name}, "name")
	if not existing:
		cust = frappe.get_doc({
			"doctype":        "Customer",
			"customer_name":  name,
			"customer_type":  "Company",
			"customer_group": _default_customer_group(),
			"territory":      _default_territory(),
		})
		if doc.inquiry:
			opp = frappe.db.get_value(
				"Opportunity", doc.inquiry, ["opportunity_from", "party_name"], as_dict=True
			) or {}
			if opp.get("opportunity_from") == "Lead" and opp.get("party_name") \
					and frappe.db.has_column("Customer", "lead_name"):
				cust.lead_name = opp["party_name"]
		cust.insert(ignore_permissions=True)
		existing = cust.name

	frappe.db.set_value("Savinda Quotation", quotation, "customer", existing)
	frappe.db.commit()
	return {"customer": existing}


def _ci_packing(cost_item):
	"""Packing Info snapshot from the (final, saved) cost Item — keyed for Sales Order Item
	custom fields. Empty dict when unavailable."""
	if not cost_item or not frappe.db.exists("cost Item", cost_item):
		return {}
	d = frappe.db.get_value(
		"cost Item", cost_item,
		["packing_type", "winding_direction", "pcs_per_role", "up", "is_printed"],
		as_dict=True,
	) or {}
	return {
		"custom_packing_type":      d.get("packing_type") or "",
		"custom_winding_direction": d.get("winding_direction") or "",
		"custom_pcs_per_role":      d.get("pcs_per_role") or 0,
		"custom_up":                d.get("up") or 0,
		"custom_is_printed":        d.get("is_printed") or "",
	}


@frappe.whitelist()
def get_quotation_fg_items(quotation):
	"""Return every FG item tied to this quotation's cost items — including
	variant FGs (Item.custom_cost_item) that aren't on a quotation row."""
	doc = frappe.get_doc("Savinda Quotation", quotation)

	ci_info = {}
	packing_cache = {}
	fgs = {}

	def _pk(cost_item):
		if cost_item not in packing_cache:
			packing_cache[cost_item] = _ci_packing(cost_item)
		return packing_cache[cost_item]

	for row in doc.items:
		if row.cost_item and row.cost_item not in ci_info:
			ci_info[row.cost_item] = {
				"qty":  flt(row.qty),
				# Company-base (LKR) rate — the Sales Order divides it by conversion_rate.
				"rate": flt(row.base_selling_price) or flt(row.selling_price),
				"cb":   row.calculation_breakdown or "",
			}
		if row.finish_good and row.finish_good not in fgs:
			fg = {
				"item_code":             row.finish_good,
				"item_name":             row.item_name or row.finish_good,
				"qty":                   flt(row.qty),
				"rate":                  flt(row.base_selling_price) or flt(row.selling_price),
				"cost_item":             row.cost_item or "",
				"calculation_breakdown": row.calculation_breakdown or "",
			}
			fg.update(_pk(row.cost_item or ""))
			fgs[row.finish_good] = fg

	if ci_info and frappe.db.has_column("Item", "custom_cost_item"):
		for it in frappe.get_all(
			"Item",
			filters={"custom_cost_item": ["in", list(ci_info.keys())]},
			fields=["name", "item_name", "custom_cost_item"],
		):
			if it.name in fgs:
				continue
			info = ci_info.get(it.custom_cost_item, {})
			fg = {
				"item_code":             it.name,
				"item_name":             it.item_name or it.name,
				"qty":                   info.get("qty", 0),
				"rate":                  info.get("rate", 0),
				"cost_item":             it.custom_cost_item,
				"calculation_breakdown": info.get("cb", ""),
			}
			fg.update(_pk(it.custom_cost_item))
			fgs[it.name] = fg

	return list(fgs.values())
