"""
Manufacturing module API — FG item creation, BOM builder helpers.
"""
import frappe


@frappe.whitelist()
def create_fg_item(item_name, description, item_group, department, stock_uom="Nos"):
	"""
	Create a Finished Good ERPNext Item with all mandatory custom fields resolved.
	- custom_department_abbr  fetched from Department.custom_abbr
	- custom_item_group_abbr  fetched from Item Group.custom_abbr
	Item code is auto-generated by ERPNext naming series.
	"""
	if not item_name:
		frappe.throw("Item Name is required")
	if not item_group:
		frappe.throw("Item Group is required")
	if not department:
		frappe.throw("Department is required")

	# Resolve abbreviations from the linked masters
	item_group_abbr = frappe.db.get_value("Item Group", item_group, "custom_abbr") or ""
	dept_abbr       = frappe.db.get_value("Department", department, "custom_abbr") or ""

	doc = frappe.get_doc({
		"doctype":                "Item",
		"item_name":              item_name,
		"description":            description or item_name,
		"item_group":             item_group,
		"stock_uom":              stock_uom or "Nos",
		"is_stock_item":          1,
		"is_sales_item":          1,
		"is_purchase_item":       0,
		"custom_department":      department,
		"custom_department_abbr": dept_abbr,
		"custom_item_group_abbr": item_group_abbr,
	})
	doc.insert(ignore_permissions=True)
	frappe.db.commit()

	return {"item_code": doc.name, "item_name": doc.item_name}
